
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 03 08:50:04 EST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 14;
  public static final int ELSE = 16;
  public static final int PLUS = 2;
  public static final int INT = 22;
  public static final int RPAREN = 7;
  public static final int SEMI = 9;
  public static final int IDENTIFIER = 24;
  public static final int END = 19;
  public static final int RETURN = 17;
  public static final int IF = 15;
  public static final int LPAREN = 6;
  public static final int WRITE = 13;
  public static final int QUOTE = 26;
  public static final int BEGIN = 18;
  public static final int STRING = 21;
  public static final int COMMA = 8;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int NEQUAL = 12;
  public static final int DIVIDE = 5;
  public static final int MAIN = 20;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int REAL = 23;
  public static final int EEQUAL = 11;
}

